name: developCleanTest

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  cleanTest:
    runs-on: macos-latest

    strategy:
        matrix:
           destination: ["platform=iOS Simulator,name=iPhone 8,OS=14.0.1"]

    env:
        DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer
        PROJECT: App/App.xcodeproj
        SCHEME: App
        CONFIGURATION: Debug

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Install xcpretty
      run: sudo gem install xcpretty
    
    - name: Cache Node Modules
      uses: actions/cache@v3
      with:
        path: .build
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
            ${{ runner.os }}-spm-
      
    - name: Xcodebuild Clean Test
      run: xcodebuild clean test
           -project ${{ env.PROJECT }}
           -scheme ${{ env.SCHEME }}
           -configuration ${{ env.CONFIGURATION }}
           -destination ${{ matrix.destination }}
           -enableCodeCoverage YES 
           -showBuildTimingSummary 
           -resolvePackageDependencies | xcpretty --color --test
        
   
